version: '2'
services:
  web:
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes_from:
      - php
    depends_on:
      - php

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./web:/var/www/html/web
<<<<<<< HEAD
<<<<<<< HEAD
=======
    depends_on:
      - db
>>>>>>> Lesson 5: Customize your PHP container

  db:
    image: mariadb:10.1.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

volumes:
  mysql-data:
    driver: local
=======
>>>>>>> Lesson 3:  Adding a PHP container
