version: '2'
services:
  web:
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html/web
    depends_on:
      - php
    environment:
      NGINX_DOCROOT: web
      NGINX_SERVER_NAME: localhost
      # Set to the same as the PHP_POST_MAX_SIZE, but use lowercase "m"
      NGINX_MAX_BODY_SIZE: 16m

  php:
    image: php:7.0-fpm
    expose:
      - 9000
    volumes:
      - ./web:/var/www/html/web

  db:
    image: mariadb:10.1.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - mysql-data:/var/lib/mysql
      - .db:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

volumes:
  mysql-data:
    driver: local
