smtp_on: true
smtp_host: mailhog
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_username: ''
smtp_password: ''
smtp_from: no-reply@example.com
smtp_fromname: DockerDrop
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
